---
- name: Install required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - apache2

- name: Enable necessary apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - ssl
    - headers
    - rewrite

- name: Create DocumentRoot directory
  ansible.builtin.file:
    path: "{{ apache_docroot }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Deploy SSL virtual host configuration
  ansible.builtin.template:
    src: cofezuwo.org.conf.j2
    dest: "/etc/apache2/sites-available/{{ apache_domain }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Reload Apache

- name: Deploy git SSL virtual host configuration
  ansible.builtin.template:
    src: git.cofezuwo.org.conf.j2
    dest: "/etc/apache2/sites-available/git.{{ apache_domain }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Reload Apache

- name: Enable SSL virtual host
  ansible.builtin.command: a2ensite {{ apache_domain }}.conf
  args:
    creates: "/etc/apache2/sites-enabled/{{ apache_domain }}.conf"
  notify: Reload Apache

- name: Enable git SSL virtual host
  ansible.builtin.command: a2ensite git.{{ apache_domain }}.conf
  args:
    creates: "/etc/apache2/sites-enabled/git.{{ apache_domain }}.conf"
  notify: Reload Apache

- name: Disable default virtual host
  ansible.builtin.command: a2dissite 000-default.conf
  notify: Reload Apache
