---
- name: Install admin packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - htop
    - neofetch
    - vim
    - curl
    - ufw
    - fail2ban
    - monit

- name: Install Netdata via kickstart script
  ansible.builtin.shell: |
    bash <(curl -Ss https://get.netdata.cloud/kickstart.sh) --dont-wait
  args:
    executable: /bin/bash

- name: Set default incoming policy
  ufw:
    direction: incoming
    policy: "deny"

- name: Set default outgoing policy
  ufw:
    direction: outgoing
    policy: "allow"

- name: Allow selected ports
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ ufw_allowed_ports }}"

- name: Enable ufw
  ufw:
    state: enabled
    policy: deny
    direction: incoming
    logging: on
